name: Domain Configuration UI
description: 'Allows saving of domain specific configuration through the UI.'
type: module
package: Domain
core_version_requirement: ^8 || ^9 || ^10
dependencies:
  - domain_config
